# frozen_string_literal: true

source "https://rubygems.org/" do
    gem 'aws-sdk', '~> 3.0.1'
    gem 'awspec', '~> 1.9'
    gem 'kitchen-terraform', '~> 3.3'
    gem 'kitchen-verifier-awspec', '~> 0.1.1'
    gem 'rhcl', '~> 0.1.0' # ruby hcl parser
end
