apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        app: weave-scope
        name: weave-scope-app
        weave-cloud-component: scope
        weave-scope-component: app
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-02a77fe",
            "original-request": {
              "url": "/k8s/scope.yaml",
              "date": "Mon Feb 13 2017 22:02:17 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            app: weave-scope
            name: weave-scope-app
            weave-cloud-component: scope
            weave-scope-component: app
        spec:
          containers:
            - name: app
              image: 'weaveworks/scope:1.2.0'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-probe'
              ports:
                - containerPort: 4040
                  protocol: TCP
      replicas: 1
    apiVersion: extensions/v1beta1
    kind: Deployment
  - metadata:
      labels:
        app: weave-scope
        name: weave-scope-app
        weave-cloud-component: scope
        weave-scope-component: app
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-02a77fe",
            "original-request": {
              "url": "/k8s/scope.yaml",
              "date": "Mon Feb 13 2017 22:02:17 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      ports:
        - name: app
          port: 80
          targetPort: 4040
          protocol: TCP
      selector:
        app: weave-scope
        name: weave-scope-app
        weave-cloud-component: scope
        weave-scope-component: app
    apiVersion: v1
    kind: Service
  - metadata:
      labels:
        app: weave-scope
        name: weave-scope-agent
        weave-cloud-component: scope
        weave-scope-component: agent
      name: weave-scope-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-02a77fe",
            "original-request": {
              "url": "/k8s/scope.yaml",
              "date": "Mon Feb 13 2017 22:02:17 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            app: weave-scope
            name: weave-scope-agent
            weave-cloud-component: scope
            weave-scope-component: agent
        spec:
          containers:
            - name: agent
              image: 'weaveworks/scope:1.2.0'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - >-
                  $(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: scope-plugins
                  mountPath: /var/run/scope/plugins
          volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
            - name: scope-plugins
              hostPath:
                path: /var/run/scope/plugins
          hostPID: true
          hostNetwork: true
    apiVersion: extensions/v1beta1
    kind: DaemonSet
