apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ template "fullname" . }}-fluentd"
data:
  elasticsearch_host: "{{ .Values.Elasticsearch.Host }}"
  elasticsearch_port: "{{ .Values.Elasticsearch.Port }}"
  source_tag: "{{ template "fullname" . }}"
  fluent.conf: |
    <source>
      type tail
      format none
      path /var/log/shiny-server/*
      pos_file /var/log/shiny-server/fluentd.pos
      read_from_head true
      tag "#{ENV['FLUENT_SOURCE_TAG']}"
    </source>

    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 5s
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>
